export const SET_ADS = 'SET_ADS';
export const SET_IS_LOADED = 'SET_IS_LOADED';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_HORIZONTAL_ORIENTATION = 'SET_HORIZONTAL_ORIENTATION';
export const SET_VERTICAL_ORIENTATION = 'SET_VERTICAL_ORIENTATION';
export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
export const SET_FAVOURITES = 'SET_FAVOURITES';
export const SET_ABOUT_TEXT = 'SET_ABOUT_TEXT';
export const SET_NEWS = 'SET_NEWS';
export const PAGINATE_SALE = 'PAGINATE_SALE,';
export const PAGINATE_RENT = 'PAGINATE_RENT,';
export const PAGINATE_DAILYRENT = 'PAGINATE_DAILYRENT,';
export const PAGINATE_NEWS = 'PAGINATE_NEWS,';
export const PAGINATE_COMMON = 'PAGINATE_COMMON,';

export const SORT_LOW_PRICE = 'SORT_LOW_PRICE';
export const SORT_HIGHT_PRICE = 'SORT_HIGH_PRICE';
export const SORT_PRICE = 'SORT_PRICE';
export const FILTER_ID = 'FILTER_ID';

// export const SET_SELECTED_PRICE = 'SET_SELECTED_PRICE';

export const SORT_BY_TODAY = "SORT_BY_TODAY";
export const SORT_BY_WEEK = "SORT_BY_WEEK";
export const SORT_BY_MOUNTH = "SORT_BY_MOUNTH";

export const ACTIVE_TOP_FILTER_PRICE = "ACTIVE_TOP_FILTER_PRICE";
export const ACTIVE_TOP_FILTER_DATE = "ACTIVE_TOP_FILTER_DATE";

export const FILTER_CATEGORY_NEWS = "FILTER_CATEGORY_NEWS";
export const ACTIVE_CATEGORY_NEWS = "ACTIVE_CATEGORY_NEWS";

export const SORT_TYPE_HOUSE = "SORT_TYPE_HOUSE";
export const SORT_TYPE_APARTMENT = "SORT_TYPE_APARTMENT";
export const SORT_STATUS_RENT = "SORT_STATUS_RENT";
export const SORT_STATUS_SALE = "SORT_STATUS_SALE";

export const RESET_FILTERS = "RESET_FILTERS";

export const SORT_CITY_KIEV = "SORT_CITY_KIEV";
export const SORT_CITY_KHARKOV = "SORT_CITY_KHARKOV";
export const SORT_CITY_DNEPR = "SORT_CITY_DNEPR";
export const SORT_CITY_LVOV = "SORT_CITY_LVOV";
export const SORT_CITY_ODESSA = "SORT_CITY_ODESSA";


//main filter
export const FILTER_TYPE = "FILTER_TYPE";
export const FILTER_STATUS = "FILTER_STATUS";

export const FILTER_STATUS_RENT = "FILTER_STATUS_RENT";
export const FILTER_STATUS_SALE = "FILTER_STATUS_SALE";
export const FILTER_STATUS_DAILYRENT = "FILTER_STATUS_DAILYRENT";

export const FILTER_TOTAL_AREA = "FILTER_TOTAL_AREA";
export const FILTER_FLOOR = "FILTER_FLOOR";
export const FILTER_ROOM = "FILTER_ROOM";
export const FILTER_PROP_WALLS = "FILTER_PROP_WALLS";
export const FILTER_HEATING = "FILTER_HEATING";
export const FILTER_CEILING_HEIGHT = "FILTER_CEILING_HEIGHT";
export const FILTER_BUILDING = "FILTER_BUILDING";
export const FILTER_OFFER = "FILTER_OFFER";

export const FILTER_REGION = "FILTER_REGION";
export const FILTER_CITY = "FILTER_CITY";
export const FILTER_DISTRICT = "FILTER_DISTRICT";



export const FILTER_PRICE_FROM = "FILTER_PRICE_FROM";
export const FILTER_PRICE_TO = "FILTER_PRICE_TO";



export const SET_FEATURES = "SET_FEATURES";
export const SET_TYPETRANSACTION = "SET_TYPETRANSACTION";

export const ACTIVE_MAIN_FORM = "ACTIVE_MAIN_FORM";
export const ACTIVE_REG_FORM = "ACTIVE_MAIN_FORM";

export const IS_LOGGED = "IS_LOGGED";



