export const SET_ADS = 'SET_ADS';
export const SET_IS_LOADED = 'SET_IS_LOADED';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_HORIZONTAL_ORIENTATION = 'SET_HORIZONTAL_ORIENTATION';
export const SET_VERTICAL_ORIENTATION = 'SET_VERTICAL_ORIENTATION';
export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
export const SET_ABOUT_TEXT = 'SET_ABOUT_TEXT';
export const SET_NEWS = 'SET_NEWS';
export const PAGINATE_SALE = 'PAGINATE_SALE,';
export const PAGINATE_RENT = 'PAGINATE_RENT,';
export const PAGINATE_DAILYRENT = 'PAGINATE_DAILYRENT,';
export const PAGINATE_NEWS = 'PAGINATE_NEWS,';

export const SORT_LOW_PRICE = 'SORT_LOW_PRICE';
export const SORT_HIGHT_PRICE = 'SORT_HIGH_PRICE';
// export const SET_SELECTED_PRICE = 'SET_SELECTED_PRICE';

export const SORT_BY_TODAY = "SORT_BY_TODAY";
export const SORT_BY_WEEK = "SORT_BY_WEEK";
export const SORT_BY_MOUNTH = "SORT_BY_MOUNTH";

export const ACTIVE_TOP_FILTER_PRICE = "ACTIVE_TOP_FILTER_PRICE";
export const ACTIVE_TOP_FILTER_DATE = "ACTIVE_TOP_FILTER_DATE";

export const FILTER_CATEGORY_NEWS = "FILTER_CATEGORY_NEWS";
export const FILTER_CATEGORY_NEWS_BY_NEWS = "FILTER_CATEGORY_NEWS_BY_NEWS";
export const FILTER_CATEGORY_NEWS_BY_TIPSGKH = "FILTER_CATEGORY_NEWS_BY_TIPSGKH";
export const FILTER_CATEGORY_NEWS_BY_NEWBUILD = "FILTER_CATEGORY_NEWS_BY_NEWBUILD";
export const FILTER_CATEGORY_NEWS_BY_MARKET = "FILTER_CATEGORY_NEWS_BY_MARKET";
export const FILTER_CATEGORY_NEWS_BY_ANLITIC = "FILTER_CATEGORY_NEWS_BY_ANLITIC";
export const FILTER_CATEGORY_NEWS_BY_TIPS_ARRANGEMENT = "FILTER_CATEGORY_NEWS_BY_TIPS_ARRANGEMENT";
export const FILTER_CATEGORY_NEWS_BY_FINANCE = "FILTER_CATEGORY_NEWS_BY_FINANCE";

export const SORT_TYPE_RENT = "SORT_TYPE_RENT";
export const SORT_TYPE_SELL = "SORT_TYPE_SELL";
export const SORT_STATUS_HOUSE = "SORT_STATUS_HOUSE";
export const SORT_STATUS_APARTMENT = "SORT_STATUS_APARTMENT";

export const RESET_FILTERS = "RESET_FILTERS";

export const SORT_LOCATION_KIEV = "SORT_LOCATION_KIEV";
export const SORT_LOCATION_KHARKOV = "SORT_LOCATION_KHARKOV";
export const SORT_LOCATION_DNEPR = "SORT_LOCATION_DNEPR";
export const SORT_LOCATION_LVOV = "SORT_LOCATION_LVOV";
export const SORT_LOCATION_ODESSA = "SORT_LOCATION_ODESSA";


//main filter
export const FILTER_TYPE_HOUSE = "FILTER_TYPE_HOUSE";
export const FILTER_TYPE_APPARTMENT = "FILTER_TYPE_APPARTMENT";
export const FILTER_TYPE_COMMERCE = "FILTER_TYPE_COMMERCE";

export const FILTER_STATUS_RENT = "FILTER_STATUS_RENT";
export const FILTER_STATUS_SALE = "FILTER_STATUS_SALE";
export const FILTER_STATUS_DAILYRENT = "FILTER_STATUS_DAILYRENT";